#!/bin/sh

echo "Running set view test include_docs.py\n"
./include_docs.py

echo "Running set view test stale.py\n"
./stale.py

echo "Running set view test updates.py\n"
./updates.py

echo "Running set view test passive_partitions.py\n"
./passive_partitions.py

echo "Running set view test passive_partitions_update.py\n"
./passive_partitions_update.py

echo "Running set view test cleanup.py\n"
./cleanup.py

echo "Running set view test compaction.py\n"
./compaction.py

echo "Running set view test compaction_transitions.py\n"
./compaction_transitions.py

echo "Running set view test filter_partitions.py\n"
./filter_partitions.py

echo "Running set view test view_merge.py\n"
./view_merge.py
